"""Application-layer exception types."""

from app.application.exceptions.base import ApplicationError
from app.application.exceptions.product_remediation import (
    ProductDataIntegrityError,
    ProductVariantResolutionError,
    ProductWriteAuthenticationError,
    ProductWriteAuthorizationError,
    ProductWriteError,
    ProductWriteSafetyGateError,
    ProductWriteTransportError,
    ProductWriteUnexpectedErpError,
    ProductWriteValidationError,
    SupplierInfoAmbiguityError,
    SupplierInfoDataIntegrityError,
    SupplierInfoDuplicateRaceError,
    SupplierInfoWriteAuthenticationError,
    SupplierInfoWriteAuthorizationError,
    SupplierInfoWriteError,
    SupplierInfoWriteTransportError,
    SupplierInfoWriteUnexpectedErpError,
    SupplierInfoWriteValidationError,
)
from app.application.exceptions.supplier_partner import (
    SupplierPartnerAmbiguityError,
    SupplierPartnerDataIntegrityError,
    SupplierPartnerDuplicateRaceError,
    SupplierPartnerInactiveError,
    SupplierPartnerWriteAuthenticationError,
    SupplierPartnerWriteAuthorizationError,
    SupplierPartnerWriteError,
    SupplierPartnerWriteSafetyGateError,
    SupplierPartnerWriteTransportError,
    SupplierPartnerWriteUnexpectedErpError,
    SupplierPartnerWriteValidationError,
)

__all__ = [
    "ApplicationError",
    "ProductDataIntegrityError",
    "ProductVariantResolutionError",
    "ProductWriteAuthenticationError",
    "ProductWriteAuthorizationError",
    "ProductWriteError",
    "ProductWriteSafetyGateError",
    "ProductWriteTransportError",
    "ProductWriteUnexpectedErpError",
    "ProductWriteValidationError",
    "SupplierInfoAmbiguityError",
    "SupplierInfoDataIntegrityError",
    "SupplierInfoDuplicateRaceError",
    "SupplierInfoWriteAuthenticationError",
    "SupplierInfoWriteAuthorizationError",
    "SupplierInfoWriteError",
    "SupplierInfoWriteTransportError",
    "SupplierInfoWriteUnexpectedErpError",
    "SupplierInfoWriteValidationError",
    "SupplierPartnerAmbiguityError",
    "SupplierPartnerDataIntegrityError",
    "SupplierPartnerDuplicateRaceError",
    "SupplierPartnerInactiveError",
    "SupplierPartnerWriteAuthenticationError",
    "SupplierPartnerWriteAuthorizationError",
    "SupplierPartnerWriteError",
    "SupplierPartnerWriteSafetyGateError",
    "SupplierPartnerWriteTransportError",
    "SupplierPartnerWriteUnexpectedErpError",
    "SupplierPartnerWriteValidationError",
]
